[versions]
accompanist = "0.8.1"
androidxactivity = "1.3.0-rc01"
androidxfragment = "1.4.0-alpha04"
androidxlifecycle = "2.4.0-alpha02"
androidxnavigation = "2.4.0-alpha04"
androidxtest = "1.4.0"
coil = "1.2.2"
compose = "1.0.0-rc01"
coroutines = "1.5.0"
dagger = "2.37"
junit5 = "5.8.0-M1"
kotlin = "1.5.10"
okhttp = "5.0.0-alpha.2"
retrofit = "2.9.0"
serialization = "1.2.1"
sqldelight = "1.5.0"
timber = "5.0.0-SNAPSHOT"

[libraries]
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

android-gradlePlugin = "com.android.tools.build:gradle:7.1.0-alpha02"

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxactivity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxactivity" }
androidx-core = "androidx.core:core-ktx:1.7.0-alpha01"
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxfragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidxfragment" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }

androidx-navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref = "androidxnavigation" }

androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha08"

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxtest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }

anvil = "com.squareup.anvil:gradle-plugin:2.3.3"

ben-gradlePlugin = "com.github.ben-manes:gradle-versions-plugin:0.39.0"
byteUnits = "com.jakewharton.byteunits:byteunits:0.9.1"

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }

compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-iconset = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui-test-core = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }

detekt = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.18.0-RC1"

junit-junit = "junit:junit:4.13"
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junit-jupiter-runtime = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlin-serialization-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-time = "org.jetbrains.kotlinx:kotlinx-datetime:0.2.1"

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.7"

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit-client = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

spotless = "com.diffplug.spotless:spotless-plugin-gradle:5.14.1"

sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqlDelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqlDelight-gradlePlugin = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqlDelight-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }

timber-android = { module = "com.jakewharton.timber:timber-android", version.ref = "timber" }
timber-common = { module = "com.jakewharton.timber:timber-common", version.ref = "timber" }
timber-jdk = { module = "com.jakewharton.timber:timber-jdk", version.ref = "timber" }

truth = "com.google.truth:truth:1.1.3"
