[versions]
# Android Components
activity = "1.5.0-alpha03"
androidBuild = "7.3.0-alpha05"
core = "1.9.0-alpha01"
fragment = "1.5.0-alpha03"
lifecycle = "2.4.0-beta01"
paging = "1.0.0-alpha12"

# Compose Components
accompanist = "0.21.3-beta"
compose = "1.2.0-alpha01"
composeSnapshot = "-"

# DI components
anvil = "2.4.0-M1"
dagger = "2.41"

# Image Component
coil = "2.0.0-rc01"

# Animations
lottie = "4.1.0"

# Core Components
coroutines = "1.6.0"
kotlin = "1.6.10"
time = "0.3.2"

# Network Components
moshi = "1.13.0"
moshix = "0.17.0"
okhttp = "5.0.0-alpha.5"
retrofit = "2.9.0"
sqldelight = "1.5.3"

# Navigation Component
workflow = "1.6.0"

# Helper Components
byteUnits = "0.9.1"
logcat = "0.1"

# Testing Components
androidxJunit = "1.1.4-alpha04"
espresso = "3.5.0-alpha04"
androidJunit5 = "1.3.0"
androidJunit5ClassPath = "1.8.2.0"
androidJunit5Compose = "1.0.0-SNAPSHOT"
androidxOrchestrator = "1.4.2-alpha01"
androidxRules = "1.4.1-alpha04"
androidxRunner = "1.5.0-alpha01"
androidxTest = "1.4.1-alpha04"
junit5 = "5.8.2"
truth = "1.1.3"

# Code Health Components
ben = "0.42.0"
detekt = "1.20.0-RC1"
leakCanary = "2.8.1"
spotless = "6.3.0"

[libraries]
accompanist-drawable = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-classpath = { module = "com.android.tools.build:gradle", version.ref = "androidBuild" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }

androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }

androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxJunit" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxOrchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxRules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxRunner" }

anvil-classpath = { module = "com.squareup.anvil:gradle-plugin", version.ref = "anvil" }

ben-classpath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "ben" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-iconset = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui-test-core = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }

detekt-classpath = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

byteUnits = { module = "com.jakewharton.byteunits:byteunits", version.ref = "byteUnits" }

junit5-android-classpath = { module = "de.mannodermaus.gradle.plugins:android-junit5", version.ref = "androidJunit5ClassPath" }
junit5-android-compose = { module = "de.mannodermaus.junit5:android-test-compose", version.ref = "androidJunit5Compose" }
junit5-android-core = { module = "de.mannodermaus.junit5:android-test-core", version.ref = "androidJunit5" }
junit5-android-runner = { module = "de.mannodermaus.junit5:android-test-runner", version.ref = "androidJunit5" }
junit5-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-jupiter-runtime = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-classpath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-time = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "time" }

leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }

lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-client = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshix-sealed-codegen = { module = "dev.zacsweers.moshix:moshi-sealed-codegen", version.ref = "moshix" }
moshix-sealed-runtime = { module = "dev.zacsweers.moshix:moshi-sealed-runtime", version.ref = "moshix" }

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit-client = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

spotless-classpath = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqlDelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqlDelight-classpath = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqlDelight-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

workflow-core = { module = "com.squareup.workflow1:workflow-core-jvm", version.ref = "workflow" }
workflow-runtime = { module = "com.squareup.workflow1:workflow-runtime-jvm", version.ref = "workflow" }
workflow-test = { module = "com.squareup.workflow1:workflow-testing-jvm", version.ref = "workflow" }
workflow-tracing = { module = "com.squareup.workflow1:workflow-tracing", version.ref = "workflow" }
workflow-ui-compose-core = { module = "com.squareup.workflow1:workflow-ui-compose", version.ref = "workflow" }
workflow-ui-compose-tooling = { module = "com.squareup.workflow1:workflow-ui-compose-tooling", version.ref = "workflow" }
workflow-ui-core-android = { module = "com.squareup.workflow1:workflow-ui-core-android", version.ref = "workflow" }
workflow-ui-core-common = { module = "com.squareup.workflow1:workflow-ui-core-common-jvm", version.ref = "workflow" }
workflow-ui-radiography = { module = "com.squareup.workflow1:workflow-ui-radiography", version.ref = "workflow" }
