[versions]
accompanist = "0.16.0"
androidxactivity = "1.3.1"
androidxfragment = "1.4.0-alpha07"
androidxlifecycle = "2.4.0-alpha03"
androidxnavigation = "2.4.0-alpha07"
androidxtest = "1.4.1-alpha01"
coil = "1.3.2"
compose = "1.1.0-alpha01"
composesnapshot = "-"
coroutines = "1.5.1"
dagger = "2.38.1"
junit5 = "5.8.0-RC1"
kotlin = "1.5.21"
moshi = "1.12.0"
moshix = "0.12.2"
okhttp = "5.0.0-alpha.2"
retrofit = "2.9.0"
sqldelight = "1.5.1"
timber = "5.0.1"

[libraries]
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder = { module = "com.google.accompanist:accompanist-placeholder", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

android-classpath = "com.android.tools.build:gradle:7.1.0-alpha09"

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxactivity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxactivity" }
androidx-core = "androidx.core:core-ktx:1.7.0-alpha01"
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxfragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidxfragment" }

androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }

androidx-navigation-compose = {module = "androidx.navigation:navigation-compose", version.ref = "androidxnavigation" }

androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha12"

androidx-test-core = { module = "androidx.test:core", version.ref = "androidxtest" }
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.5.0-alpha01"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.4-alpha01"
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxtest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }

anvil-classpath = "com.squareup.anvil:gradle-plugin:2.3.3"

ben-classpath = "com.github.ben-manes:gradle-versions-plugin:0.39.0"

byteUnits = "com.jakewharton.byteunits:byteunits:0.9.1"

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }

compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-iconset = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable", version.ref = "compose" }
compose-ui-test-core = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }

dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }

detekt-classpath = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.18.0"

junit-junit = "junit:junit:4.13"
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junit-jupiter-runtime = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-extensions = { module = "org.jetbrains.kotlin:kotlin-android-extensions", version.ref = "kotlin" }
kotlin-classpath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-time = "org.jetbrains.kotlinx:kotlinx-datetime:0.2.1"

leakCanary = "com.squareup.leakcanary:leakcanary-android:2.7"

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-client = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshix-ksp = { module = "dev.zacsweers.moshix:moshi-ksp", version.ref = "moshix" }
moshix-sealed-runtime = { module = "dev.zacsweers.moshix:moshi-sealed-runtime", version.ref = "moshix" }
moshix-sealed-ksp = { module = "dev.zacsweers.moshix:moshi-sealed-ksp", version.ref = "moshix" }

okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

retrofit-client = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

spotless-classpath = "com.diffplug.spotless:spotless-plugin-gradle:5.14.3"

sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqlDelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqlDelight-classpath = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqlDelight-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

truth = "com.google.truth:truth:1.1.3"
